modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/FaArMa/HandcuffsMod/issues"

[[mods]]
modId="handcuffsmod"
version="${file.jarVersion}"
displayName="Handcuffs Mod"
displayURL="https://github.com/FaArMa/HandcuffsMod"
logoFile="handcuffsmod.png"
credits="<Autor Desconocido> por el modelo y texturas"
authors="FaArMa"
description='''
Permite esposar jugadores para que no puedan moverse ni interactuar con el entorno
'''

[[dependencies.handcuffsmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.handcuffsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.handcuffsmod]]
    modId="pehkui"
    mandatory=true
    versionRange="[3.7.8+1.16.5-forge,)"
    ordering="NONE"
    side="BOTH"
